<?php 
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("At")){ $vlPasNacAt=$vlPasNacAt+str_replace(",",".",$objPasNac->total);$corPasNacAt=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Bf")){ $vlPasNacBf=$vlPasNacBf+str_replace(",",".",$objPasNac->total);$corPasNacBf="";}}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Bm")){ $vlPasNacBm=$vlPasNacBm+str_replace(",",".",$objPasNac->total);$corPasNacBm=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Boc")){ $vlPasNacBoc=$vlPasNacBoc+str_replace(",",".",$objPasNac->total);$corPasNacBoc=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Cic")){ $vlPasNacCic=$vlPasNacCic+str_replace(",",".",$objPasNac->total);$corPasNacCic=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Esg")){ $vlPasNacEsg=$vlPasNacEsg+str_replace(",",".",$objPasNac->total);$corPasNacEsg=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Fuc")){ $vlPasNacFuc=$vlPasNacFuc+str_replace(",",".",$objPasNac->total);$corPasNacFuc=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Fus")){ $vlPasNacFus=$vlPasNacFus+str_replace(",",".",$objPasNac->total);$corPasNacFus=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Gof")){ $vlPasNacGof=$vlPasNacGof+str_replace(",",".",$objPasNac->total);$corPasNacGof=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Gom")){ $vlPasNacGom=$vlPasNacGom+str_replace(",",".",$objPasNac->total);$corPasNacGom=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Halt")){ $vlPasNacHalt=$vlPasNacHalt+str_replace(",",".",$objPasNac->total);$corPasNacHalt=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Hip")){ $vlPasNacHip=$vlPasNacHip+str_replace(",",".",$objPasNac->total);$corPasNacHip=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Jud")){ $vlPasNacJud=$vlPasNacJud+str_replace(",",".",$objPasNac->total);$corPasNacJud=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Nat")){ $vlPasNacNat=$vlPasNacNat+str_replace(",",".",$objPasNac->total);$corPasNacNat=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Can")){ $vlPasNacCan=$vlPasNacCan+str_replace(",",".",$objPasNac->total);$corPasNacCan=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Thl")){ $vlPasNacThl=$vlPasNacThl+str_replace(",",".",$objPasNac->total);$corPasNacThl=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Rem")){ $vlPasNacRem=$vlPasNacRem+str_replace(",",".",$objPasNac->total);$corPasNacRem=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Rug")){ $vlPasNacRug=$vlPasNacRug+str_replace(",",".",$objPasNac->total);$corPasNacRug=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Ten")){ $vlPasNacTen=$vlPasNacTen+str_replace(",",".",$objPasNac->total);$corPasNacTen=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Tar")){ $vlPasNacTar=$vlPasNacTar+str_replace(",",".",$objPasNac->total);$corPasNacTar=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Tes")){ $vlPasNacTes=$vlPasNacTes+str_replace(",",".",$objPasNac->total);$corPasNacTes=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Vel")){ $vlPasNacVel=$vlPasNacVel+str_replace(",",".",$objPasNac->total);$corPasNacVel=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Vof")){ $vlPasNacVof=$vlPasNacVof+str_replace(",",".",$objPasNac->total);$corPasNacVof=""; }}
while($objPasNac=mysql_fetch_object($sqlPasNac)){ if(strtoupper($objPasNac->modal)== strtoupper("Vom")){ $vlPasNacVom=$vlPasNacVom+str_replace(",",".",$objPasNac->total);$corPasNacVom=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("At")){ $vlPasIntAt=$vlPasIntAt+str_replace(",",".",$objPasInt->total);$corPasIntAt=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Bf")){ $vlPasIntBf=$vlPasIntBf+str_replace(",",".",$objPasInt->total);$corPasIntBf=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Bm")){ $vlPasIntBm=$vlPasIntBm+str_replace(",",".",$objPasInt->total);$corPasIntBm=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Boc")){ $vlPasIntBoc=$vlPasIntBoc+str_replace(",",".",$objPasInt->total);$corPasIntBoc=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Cic")){ $vlPasIntCic=$vlPasIntCic+str_replace(",",".",$objPasInt->total);$corPasIntCic=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Esg")){ $vlPasIntEsg=$vlPasIntEsg+str_replace(",",".",$objPasInt->total);$corPasIntEsg=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Fuc")){ $vlPasIntFuc=$vlPasIntFuc+str_replace(",",".",$objPasInt->total);$corPasIntFuc=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Fus")){ $vlPasIntFus=$vlPasIntFus+str_replace(",",".",$objPasInt->total);$corPasIntFus=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Gof")){ $vlPasIntGof=$vlPasIntGof+str_replace(",",".",$objPasInt->total);$corPasIntGof=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Gom")){ $vlPasIntGom=$vlPasIntGom+str_replace(",",".",$objPasInt->total);$corPasIntGom=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Halt")){ $vlPasIntHalt=$vlPasIntHalt+str_replace(",",".",$objPasInt->total);$corPasIntHalt=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Hip")){ $vlPasIntHip=$vlPasIntHip+str_replace(",",".",$objPasInt->total);$corPasIntHip=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Jud")){ $vlPasIntJud=$vlPasIntJud+str_replace(",",".",$objPasInt->total);$corPasIntJud=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Nat")){ $vlPasIntNat=$vlPasIntNat+str_replace(",",".",$objPasInt->total);$corPasIntNat=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Can")){ $vlPasIntCan=$vlPasIntCan+str_replace(",",".",$objPasInt->total);$corPasIntCan=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Thl")){ $vlPasIntThl=$vlPasIntThl+str_replace(",",".",$objPasInt->total);$corPasIntThl=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Rem")){ $vlPasIntRem=$vlPasIntRem+str_replace(",",".",$objPasInt->total);$corPasIntRem=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Rug")){ $vlPasIntRug=$vlPasIntRug+str_replace(",",".",$objPasInt->total);$corPasIntRug=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Ten")){ $vlPasIntTen=$vlPasIntTen+str_replace(",",".",$objPasInt->total);$corPasIntTen=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Tar")){ $vlPasIntTar=$vlPasIntTar+str_replace(",",".",$objPasInt->total);$corPasIntTar=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Tes")){ $vlPasIntTes=$vlPasIntTes+str_replace(",",".",$objPasInt->total);$corPasIntTes=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Vel")){ $vlPasIntVel=$vlPasIntVel+str_replace(",",".",$objPasInt->total);$corPasIntVel=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Vof")){ $vlPasIntVof=$vlPasIntVof+str_replace(",",".",$objPasInt->total);$corPasIntVof=""; }}
while($objPasInt=mysql_fetch_object($sqlPasInt)){ if(strtoupper($objPasInt->modal)== strtoupper("Vom")){ $vlPasIntVom=$vlPasIntVom+str_replace(",",".",$objPasInt->total);$corPasIntVom=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("At")){ $vlHosNacAt=$vlHosNacAt+str_replace(",",".",$objHosNac->total);$corHosNacAt=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Bf")){ $vlHosNacBf=$vlHosNacBf+str_replace(",",".",$objHosNac->total);$corHosNacBf=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Bm")){ $vlHosNacBm=$vlHosNacBm+str_replace(",",".",$objHosNac->total);$corHosNacBm=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Boc")){ $vlHosNacBoc=$vlHosNacBoc+str_replace(",",".",$objHosNac->total);$corHosNacBoc=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Cic")){ $vlHosNacCic=$vlHosNacCic+str_replace(",",".",$objHosNac->total);$corHosNacCic=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Esg")){ $vlHosNacEsg=$vlHosNacEsg+str_replace(",",".",$objHosNac->total);$corHosNacEsg=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Fuc")){ $vlHosNacFuc=$vlHosNacFuc+str_replace(",",".",$objHosNac->total);$corHosNacFuc=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Fus")){ $vlHosNacFus=$vlHosNacFus+str_replace(",",".",$objHosNac->total);$corHosNacFus=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Gof")){ $vlHosNacGof=$vlHosNacGof+str_replace(",",".",$objHosNac->total);$corHosNacGof=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Gom")){ $vlHosNacGom=$vlHosNacGom+str_replace(",",".",$objHosNac->total);$corHosNacGom=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Halt")){ $vlHosNacHalt=$vlHosNacHalt+str_replace(",",".",$objHosNac->total);$corHosNacHalt=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Hip")){ $vlHosNacHip=$vlHosNacHip+str_replace(",",".",$objHosNac->total);$corHosNacHip=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Jud")){ $vlHosNacJud=$vlHosNacJud+str_replace(",",".",$objHosNac->total);$corHosNacJud=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Nat")){ $vlHosNacNat=$vlHosNacNat+str_replace(",",".",$objHosNac->total);$corHosNacNat=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Can")){ $vlHosNacCan=$vlHosNacCan+str_replace(",",".",$objHosNac->total);$corHosNacCan=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Thl")){ $vlHosNacThl=$vlHosNacThl+str_replace(",",".",$objHosNac->total);$corHosNacThl=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Rem")){ $vlHosNacRem=$vlHosNacRem+str_replace(",",".",$objHosNac->total);$corHosNacRem=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Rug")){ $vlHosNacRug=$vlHosNacRug+str_replace(",",".",$objHosNac->total);$corHosNacRug=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Ten")){ $vlHosNacTen=$vlHosNacTen+str_replace(",",".",$objHosNac->total);$corHosNacTen=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Tar")){ $vlHosNacTar=$vlHosNacTar+str_replace(",",".",$objHosNac->total);$corHosNacTar=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Tes")){ $vlHosNacTes=$vlHosNacTes+str_replace(",",".",$objHosNac->total);$corHosNacTes=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Vel")){ $vlHosNacVel=$vlHosNacVel+str_replace(",",".",$objHosNac->total);$corHosNacVel=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Vof")){ $vlHosNacVof=$vlHosNacVof+str_replace(",",".",$objHosNac->total);$corHosNacVof=""; }}
while($objHosNac=mysql_fetch_object($sqlHosNac)){ if(strtoupper($objHosNac->modal)== strtoupper("Vom")){ $vlHosNacVom=$vlHosNacVom+str_replace(",",".",$objHosNac->total);$corHosNacVom=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("At")){ $vlHosIntAt=$vlHosIntAt+str_replace(",",".",$objHosInt->total);$corHosIntAt=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Bf")){ $vlHosIntBf=$vlHosIntBf+str_replace(",",".",$objHosInt->total);$corHosIntBf=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Bm")){ $vlHosIntBm=$vlHosIntBm+str_replace(",",".",$objHosInt->total);$corHosIntBm=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Boc")){ $vlHosIntBoc=$vlHosIntBoc+str_replace(",",".",$objHosInt->total);$corHosIntBoc=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Cic")){ $vlHosIntCic=$vlHosIntCic+str_replace(",",".",$objHosInt->total);$corHosIntCic=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Esg")){ $vlHosIntEsg=$vlHosIntEsg+str_replace(",",".",$objHosInt->total);$corHosIntEsg=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Fuc")){ $vlHosIntFuc=$vlHosIntFuc+str_replace(",",".",$objHosInt->total);$corHosIntFuc=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Fus")){ $vlHosIntFus=$vlHosIntFus+str_replace(",",".",$objHosInt->total);$corHosIntFus=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Gof")){ $vlHosIntGof=$vlHosIntGof+str_replace(",",".",$objHosInt->total);$corHosIntGof=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Gom")){ $vlHosIntGom=$vlHosIntGom+str_replace(",",".",$objHosInt->total);$corHosIntGom=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Halt")){ $vlHosIntHalt=$vlHosIntHalt+str_replace(",",".",$objHosInt->total);$corHosIntHalt=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Hip")){ $vlHosIntHip=$vlHosIntHip+str_replace(",",".",$objHosInt->total);$corHosIntHip=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Jud")){ $vlHosIntJud=$vlHosIntJud+str_replace(",",".",$objHosInt->total);$corHosIntJud=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Nat")){ $vlHosIntNat=$vlHosIntNat+str_replace(",",".",$objHosInt->total);$corHosIntNat=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Can")){ $vlHosIntCan=$vlHosIntCan+str_replace(",",".",$objHosInt->total);$corHosIntCan=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Thl")){ $vlHosIntThl=$vlHosIntThl+str_replace(",",".",$objHosInt->total);$corHosIntThl=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Rem")){ $vlHosIntRem=$vlHosIntRem+str_replace(",",".",$objHosInt->total);$corHosIntRem=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Rug")){ $vlHosIntRug=$vlHosIntRug+str_replace(",",".",$objHosInt->total);$corHosIntRug=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Ten")){ $vlHosIntTen=$vlHosIntTen+str_replace(",",".",$objHosInt->total);$corHosIntTen=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Tar")){ $vlHosIntTar=$vlHosIntTar+str_replace(",",".",$objHosInt->total);$corHosIntTar=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Tes")){ $vlHosIntTes=$vlHosIntTes+str_replace(",",".",$objHosInt->total);$corHosIntTes=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Vel")){ $vlHosIntVel=$vlHosIntVel+str_replace(",",".",$objHosInt->total);$corHosIntVel=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Vof")){ $vlHosIntVof=$vlHosIntVof+str_replace(",",".",$objHosInt->total);$corHosIntVof=""; }}
while($objHosInt=mysql_fetch_object($sqlHosInt)){ if(strtoupper($objHosInt->modal)== strtoupper("Vom")){ $vlHosIntVom=$vlHosIntVom+str_replace(",",".",$objHosInt->total);$corHosIntVom=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("At")){ $vlAliNacAt=$vlAliNacAt+str_replace(",",".",$objAliNac->total);$corAliNacAt=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Bf")){ $vlAliNacBf=$vlAliNacBf+str_replace(",",".",$objAliNac->total);$corAliNacBf=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Bm")){ $vlAliNacBm=$vlAliNacBm+str_replace(",",".",$objAliNac->total);$corAliNacBm=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Boc")){ $vlAliNacBoc=$vlAliNacBoc+str_replace(",",".",$objAliNac->total);$corAliNacBoc=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Cic")){ $vlAliNacCic=$vlAliNacCic+str_replace(",",".",$objAliNac->total);$corAliNacCic=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Esg")){ $vlAliNacEsg=$vlAliNacEsg+str_replace(",",".",$objAliNac->total);$corAliNacEsg=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Fuc")){ $vlAliNacFuc=$vlAliNacFuc+str_replace(",",".",$objAliNac->total);$corAliNacFuc=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Fus")){ $vlAliNacFus=$vlAliNacFus+str_replace(",",".",$objAliNac->total);$corAliNacFus=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Gof")){ $vlAliNacGof=$vlAliNacGof+str_replace(",",".",$objAliNac->total);$corAliNacGof=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Gom")){ $vlAliNacGom=$vlAliNacGom+str_replace(",",".",$objAliNac->total);$corAliNacGom=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Halt")){ $vlAliNacHalt=$vlAliNacHalt+str_replace(",",".",$objAliNac->total);$corAliNacHalt=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Hip")){ $vlAliNacHip=$vlAliNacHip+str_replace(",",".",$objAliNac->total);$corAliNacHip=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Jud")){ $vlAliNacJud=$vlAliNacJud+str_replace(",",".",$objAliNac->total);$corAliNacJud=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Nat")){ $vlAliNacNat=$vlAliNacNat+str_replace(",",".",$objAliNac->total);$corAliNacNat=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Can")){ $vlAliNacCan=$vlAliNacCan+str_replace(",",".",$objAliNac->total);$corAliNacCan=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Thl")){ $vlAliNacThl=$vlAliNacThl+str_replace(",",".",$objAliNac->total);$corAliNacThl=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Rem")){ $vlAliNacRem=$vlAliNacRem+str_replace(",",".",$objAliNac->total);$corAliNacRem=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Rug")){ $vlAliNacRug=$vlAliNacRug+str_replace(",",".",$objAliNac->total);$corAliNacRug=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Ten")){ $vlAliNacTen=$vlAliNacTen+str_replace(",",".",$objAliNac->total);$corAliNacTen=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Tar")){ $vlAliNacTar=$vlAliNacTar+str_replace(",",".",$objAliNac->total);$corAliNacTar=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Tes")){ $vlAliNacTes=$vlAliNacTes+str_replace(",",".",$objAliNac->total);$corAliNacTes=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Vel")){ $vlAliNacVel=$vlAliNacVel+str_replace(",",".",$objAliNac->total);$corAliNacVel=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Vof")){ $vlAliNacVof=$vlAliNacVof+str_replace(",",".",$objAliNac->total);$corAliNacVof=""; }}
while($objAliNac=mysql_fetch_object($sqlAliNac)){ if(strtoupper($objAliNac->modal)== strtoupper("Vom")){ $vlAliNacVom=$vlAliNacVom+str_replace(",",".",$objAliNac->total);$corAliNacVom=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("At")){ $vlAliIntAt=$vlAliIntAt+str_replace(",",".",$objAliInt->total);$corAliIntAt=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Bf")){ $vlAliIntBf=$vlAliIntBf+str_replace(",",".",$objAliInt->total);$corAliIntBf=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Bm")){ $vlAliIntBm=$vlAliIntBm+str_replace(",",".",$objAliInt->total);$corAliIntBm=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Boc")){ $vlAliIntBoc=$vlAliIntBoc+str_replace(",",".",$objAliInt->total);$corAliIntBoc=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Cic")){ $vlAliIntCic=$vlAliIntCic+str_replace(",",".",$objAliInt->total);$corAliIntCic=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Esg")){ $vlAliIntEsg=$vlAliIntEsg+str_replace(",",".",$objAliInt->total);$corAliIntEsg=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Fuc")){ $vlAliIntFuc=$vlAliIntFuc+str_replace(",",".",$objAliInt->total);$corAliIntFuc=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Fus")){ $vlAliIntFus=$vlAliIntFus+str_replace(",",".",$objAliInt->total);$corAliIntFus=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Gof")){ $vlAliIntGof=$vlAliIntGof+str_replace(",",".",$objAliInt->total);$corAliIntGof=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Gom")){ $vlAliIntGom=$vlAliIntGom+str_replace(",",".",$objAliInt->total);$corAliIntGom=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Halt")){ $vlAliIntHalt=$vlAliIntHalt+str_replace(",",".",$objAliInt->total);$corAliIntHalt=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Hip")){ $vlAliIntHip=$vlAliIntHip+str_replace(",",".",$objAliInt->total);$corAliIntHip=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Jud")){ $vlAliIntJud=$vlAliIntJud+str_replace(",",".",$objAliInt->total);$corAliIntJud=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Nat")){ $vlAliIntNat=$vlAliIntNat+str_replace(",",".",$objAliInt->total);$corAliIntNat=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Can")){ $vlAliIntCan=$vlAliIntCan+str_replace(",",".",$objAliInt->total);$corAliIntCan=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Thl")){ $vlAliIntThl=$vlAliIntThl+str_replace(",",".",$objAliInt->total);$corAliIntThl=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Rem")){ $vlAliIntRem=$vlAliIntRem+str_replace(",",".",$objAliInt->total);$corAliIntRem=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Rug")){ $vlAliIntRug=$vlAliIntRug+str_replace(",",".",$objAliInt->total);$corAliIntRug=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Ten")){ $vlAliIntTen=$vlAliIntTen+str_replace(",",".",$objAliInt->total);$corAliIntTen=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Tar")){ $vlAliIntTar=$vlAliIntTar+str_replace(",",".",$objAliInt->total);$corAliIntTar=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Tes")){ $vlAliIntTes=$vlAliIntTes+str_replace(",",".",$objAliInt->total);$corAliIntTes=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Vel")){ $vlAliIntVel=$vlAliIntVel+str_replace(",",".",$objAliInt->total);$corAliIntVel=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Vof")){ $vlAliIntVof=$vlAliIntVof+str_replace(",",".",$objAliInt->total);$corAliIntVof=""; }}
while($objAliInt=mysql_fetch_object($sqlAliInt)){ if(strtoupper($objAliInt->modal)== strtoupper("Vom")){ $vlAliIntVom=$vlAliIntVom+str_replace(",",".",$objAliInt->total);$corAliIntVom=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("At")){ $vlTraNacAt=$vlTraNacAt+str_replace(",",".",$objTraNac->total);$corTraNacAt=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Bf")){ $vlTraNacBf=$vlTraNacBf+str_replace(",",".",$objTraNac->total);$corTraNacBf=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Bm")){ $vlTraNacBm=$vlTraNacBm+str_replace(",",".",$objTraNac->total);$corTraNacBm=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Boc")){ $vlTraNacBoc=$vlTraNacBoc+str_replace(",",".",$objTraNac->total);$corTraNacBoc=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Cic")){ $vlTraNacCic=$vlTraNacCic+str_replace(",",".",$objTraNac->total);$corTraNacCic=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Esg")){ $vlTraNacEsg=$vlTraNacEsg+str_replace(",",".",$objTraNac->total);$corTraNacEsg=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Fuc")){ $vlTraNacFuc=$vlTraNacFuc+str_replace(",",".",$objTraNac->total);$corTraNacFuc=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Fus")){ $vlTraNacFus=$vlTraNacFus+str_replace(",",".",$objTraNac->total);$corTraNacFus=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Gof")){ $vlTraNacGof=$vlTraNacGof+str_replace(",",".",$objTraNac->total);$corTraNacGof=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Gom")){ $vlTraNacGom=$vlTraNacGom+str_replace(",",".",$objTraNac->total);$corTraNacGom=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Halt")){ $vlTraNacHalt=$vlTraNacHalt+str_replace(",",".",$objTraNac->total);$corTraNacHalt=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Hip")){ $vlTraNacHip=$vlTraNacHip+str_replace(",",".",$objTraNac->total);$corTraNacHip=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Jud")){ $vlTraNacJud=$vlTraNacJud+str_replace(",",".",$objTraNac->total);$corTraNacJud=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Nat")){ $vlTraNacNat=$vlTraNacNat+str_replace(",",".",$objTraNac->total);$corTraNacNat=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Can")){ $vlTraNacCan=$vlTraNacCan+str_replace(",",".",$objTraNac->total);$corTraNacCan=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Thl")){ $vlTraNacThl=$vlTraNacThl+str_replace(",",".",$objTraNac->total);$corTraNacThl=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Rem")){ $vlTraNacRem=$vlTraNacRem+str_replace(",",".",$objTraNac->total);$corTraNacRem=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Rug")){ $vlTraNacRug=$vlTraNacRug+str_replace(",",".",$objTraNac->total);$corTraNacRug=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Ten")){ $vlTraNacTen=$vlTraNacTen+str_replace(",",".",$objTraNac->total);$corTraNacTen=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Tar")){ $vlTraNacTar=$vlTraNacTar+str_replace(",",".",$objTraNac->total);$corTraNacTar=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Tes")){ $vlTraNacTes=$vlTraNacTes+str_replace(",",".",$objTraNac->total);$corTraNacTes=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Vel")){ $vlTraNacVel=$vlTraNacVel+str_replace(",",".",$objTraNac->total);$corTraNacVel=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Vof")){ $vlTraNacVof=$vlTraNacVof+str_replace(",",".",$objTraNac->total);$corTraNacVof=""; }}
while($objTraNac=mysql_fetch_object($sqlTraNac)){ if(strtoupper($objTraNac->modal)== strtoupper("Vom")){ $vlTraNacVom=$vlTraNacVom+str_replace(",",".",$objTraNac->total);$corTraNacVom=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("At")){ $vlTraIntAt=$vlTraIntAt+str_replace(",",".",$objTraInt->total);$corTraIntAt=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Bf")){ $vlTraIntBf=$vlTraIntBf+str_replace(",",".",$objTraInt->total);$corTraIntBf=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Bm")){ $vlTraIntBm=$vlTraIntBm+str_replace(",",".",$objTraInt->total);$corTraIntBm=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Boc")){ $vlTraIntBoc=$vlTraIntBoc+str_replace(",",".",$objTraInt->total);$corTraIntBoc=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Cic")){ $vlTraIntCic=$vlTraIntCic+str_replace(",",".",$objTraInt->total);$corTraIntCic=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Esg")){ $vlTraIntEsg=$vlTraIntEsg+str_replace(",",".",$objTraInt->total);$corTraIntEsg=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Fuc")){ $vlTraIntFuc=$vlTraIntFuc+str_replace(",",".",$objTraInt->total);$corTraIntFuc=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Fus")){ $vlTraIntFus=$vlTraIntFus+str_replace(",",".",$objTraInt->total);$corTraIntFus=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Gof")){ $vlTraIntGof=$vlTraIntGof+str_replace(",",".",$objTraInt->total);$corTraIntGof=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Gom")){ $vlTraIntGom=$vlTraIntGom+str_replace(",",".",$objTraInt->total);$corTraIntGom=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Halt")){ $vlTraIntHalt=$vlTraIntHalt+str_replace(",",".",$objTraInt->total);$corTraIntHalt=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Hip")){ $vlTraIntHip=$vlTraIntHip+str_replace(",",".",$objTraInt->total);$corTraIntHip=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Jud")){ $vlTraIntJud=$vlTraIntJud+str_replace(",",".",$objTraInt->total);$corTraIntJud=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Nat")){ $vlTraIntNat=$vlTraIntNat+str_replace(",",".",$objTraInt->total);$corTraIntNat=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Can")){ $vlTraIntCan=$vlTraIntCan+str_replace(",",".",$objTraInt->total);$corTraIntCan=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Thl")){ $vlTraIntThl=$vlTraIntThl+str_replace(",",".",$objTraInt->total);$corTraIntThl=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Rem")){ $vlTraIntRem=$vlTraIntRem+str_replace(",",".",$objTraInt->total);$corTraIntRem=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Rug")){ $vlTraIntRug=$vlTraIntRug+str_replace(",",".",$objTraInt->total);$corTraIntRug=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Ten")){ $vlTraIntTen=$vlTraIntTen+str_replace(",",".",$objTraInt->total);$corTraIntTen=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Tar")){ $vlTraIntTar=$vlTraIntTar+str_replace(",",".",$objTraInt->total);$corTraIntTar=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Tes")){ $vlTraIntTes=$vlTraIntTes+str_replace(",",".",$objTraInt->total);$corTraIntTes=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Vel")){ $vlTraIntVel=$vlTraIntVel+str_replace(",",".",$objTraInt->total);$corTraIntVel=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Vof")){ $vlTraIntVof=$vlTraIntVof+str_replace(",",".",$objTraInt->total);$corTraIntVof=""; }}
while($objTraInt=mysql_fetch_object($sqlTraInt)){ if(strtoupper($objTraInt->modal)== strtoupper("Vom")){ $vlTraIntVom=$vlTraIntVom+str_replace(",",".",$objTraInt->total);$corTraIntVom=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("At")){ $vlSgvNacAt=$vlSgvNacAt+str_replace(",",".",$objSgvNac->total);$corSgvNacAt=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Bf")){ $vlSgvNacBf=$vlSgvNacBf+str_replace(",",".",$objSgvNac->total);$corSgvNacBf=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Bm")){ $vlSgvNacBm=$vlSgvNacBm+str_replace(",",".",$objSgvNac->total);$corSgvNacBm=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Boc")){ $vlSgvNacBoc=$vlSgvNacBoc+str_replace(",",".",$objSgvNac->total);$corSgvNacBoc=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Cic")){ $vlSgvNacCic=$vlSgvNacCic+str_replace(",",".",$objSgvNac->total);$corSgvNacCic=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Esg")){ $vlSgvNacEsg=$vlSgvNacEsg+str_replace(",",".",$objSgvNac->total);$corSgvNacEsg=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Fuc")){ $vlSgvNacFuc=$vlSgvNacFuc+str_replace(",",".",$objSgvNac->total);$corSgvNacFuc=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Fus")){ $vlSgvNacFus=$vlSgvNacFus+str_replace(",",".",$objSgvNac->total);$corSgvNacFus=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Gof")){ $vlSgvNacGof=$vlSgvNacGof+str_replace(",",".",$objSgvNac->total);$corSgvNacGof=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Gom")){ $vlSgvNacGom=$vlSgvNacGom+str_replace(",",".",$objSgvNac->total);$corSgvNacGom=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Halt")){ $vlSgvNacHalt=$vlSgvNacHalt+str_replace(",",".",$objSgvNac->total);$corSgvNacHalt=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Hip")){ $vlSgvNacHip=$vlSgvNacHip+str_replace(",",".",$objSgvNac->total);$corSgvNacHip=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Jud")){ $vlSgvNacJud=$vlSgvNacJud+str_replace(",",".",$objSgvNac->total);$corSgvNacJud=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Nat")){ $vlSgvNacNat=$vlSgvNacNat+str_replace(",",".",$objSgvNac->total);$corSgvNacNat=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Can")){ $vlSgvNacCan=$vlSgvNacCan+str_replace(",",".",$objSgvNac->total);$corSgvNacCan=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Thl")){ $vlSgvNacThl=$vlSgvNacThl+str_replace(",",".",$objSgvNac->total);$corSgvNacThl=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Rem")){ $vlSgvNacRem=$vlSgvNacRem+str_replace(",",".",$objSgvNac->total);$corSgvNacRem=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Rug")){ $vlSgvNacRug=$vlSgvNacRug+str_replace(",",".",$objSgvNac->total);$corSgvNacRug=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Ten")){ $vlSgvNacTen=$vlSgvNacTen+str_replace(",",".",$objSgvNac->total);$corSgvNacTen=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Tar")){ $vlSgvNacTar=$vlSgvNacTar+str_replace(",",".",$objSgvNac->total);$corSgvNacTar=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Tes")){ $vlSgvNacTes=$vlSgvNacTes+str_replace(",",".",$objSgvNac->total);$corSgvNacTes=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Vel")){ $vlSgvNacVel=$vlSgvNacVel+str_replace(",",".",$objSgvNac->total);$corSgvNacVel=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Vof")){ $vlSgvNacVof=$vlSgvNacVof+str_replace(",",".",$objSgvNac->total);$corSgvNacVof=""; }}
while($objSgvNac=mysql_fetch_object($sqlSgvNac)){ if(strtoupper($objSgvNac->modal)== strtoupper("Vom")){ $vlSgvNacVom=$vlSgvNacVom+str_replace(",",".",$objSgvNac->total);$corSgvNacVom=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("At")){ $vlSgvIntAt=$vlSgvIntAt+str_replace(",",".",$objSgvInt->total);$corSgvIntAt=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Bf")){ $vlSgvIntBf=$vlSgvIntBf+str_replace(",",".",$objSgvInt->total);$corSgvIntBf=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Bm")){ $vlSgvIntBm=$vlSgvIntBm+str_replace(",",".",$objSgvInt->total);$corSgvIntBm=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Boc")){ $vlSgvIntBoc=$vlSgvIntBoc+str_replace(",",".",$objSgvInt->total);$corSgvIntBoc=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Cic")){ $vlSgvIntCic=$vlSgvIntCic+str_replace(",",".",$objSgvInt->total);$corSgvIntCic=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Esg")){ $vlSgvIntEsg=$vlSgvIntEsg+str_replace(",",".",$objSgvInt->total);$corSgvIntEsg=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Fuc")){ $vlSgvIntFuc=$vlSgvIntFuc+str_replace(",",".",$objSgvInt->total);$corSgvIntFuc=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Fus")){ $vlSgvIntFus=$vlSgvIntFus+str_replace(",",".",$objSgvInt->total);$corSgvIntFus=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Gof")){ $vlSgvIntGof=$vlSgvIntGof+str_replace(",",".",$objSgvInt->total);$corSgvIntGof=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Gom")){ $vlSgvIntGom=$vlSgvIntGom+str_replace(",",".",$objSgvInt->total);$corSgvIntGom=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Halt")){ $vlSgvIntHalt=$vlSgvIntHalt+str_replace(",",".",$objSgvInt->total);$corSgvIntHalt=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Hip")){ $vlSgvIntHip=$vlSgvIntHip+str_replace(",",".",$objSgvInt->total);$corSgvIntHip=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Jud")){ $vlSgvIntJud=$vlSgvIntJud+str_replace(",",".",$objSgvInt->total);$corSgvIntJud=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Nat")){ $vlSgvIntNat=$vlSgvIntNat+str_replace(",",".",$objSgvInt->total);$corSgvIntNat=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Can")){ $vlSgvIntCan=$vlSgvIntCan+str_replace(",",".",$objSgvInt->total);$corSgvIntCan=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Thl")){ $vlSgvIntThl=$vlSgvIntThl+str_replace(",",".",$objSgvInt->total);$corSgvIntThl=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Rem")){ $vlSgvIntRem=$vlSgvIntRem+str_replace(",",".",$objSgvInt->total);$corSgvIntRem=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Rug")){ $vlSgvIntRug=$vlSgvIntRug+str_replace(",",".",$objSgvInt->total);$corSgvIntRug=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Ten")){ $vlSgvIntTen=$vlSgvIntTen+str_replace(",",".",$objSgvInt->total);$corSgvIntTen=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Tar")){ $vlSgvIntTar=$vlSgvIntTar+str_replace(",",".",$objSgvInt->total);$corSgvIntTar=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Tes")){ $vlSgvIntTes=$vlSgvIntTes+str_replace(",",".",$objSgvInt->total);$corSgvIntTes=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Vel")){ $vlSgvIntVel=$vlSgvIntVel+str_replace(",",".",$objSgvInt->total);$corSgvIntVel=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Vof")){ $vlSgvIntVof=$vlSgvIntVof+str_replace(",",".",$objSgvInt->total);$corSgvIntVof=""; }}
while($objSgvInt=mysql_fetch_object($sqlSgvInt)){ if(strtoupper($objSgvInt->modal)== strtoupper("Vom")){ $vlSgvIntVom=$vlSgvIntVom+str_replace(",",".",$objSgvInt->total);$corSgvIntVom=""; }}

//Calculo de tributos RH
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("At")){ 
$vlRhtNacAt=$vlRhtNacAt+str_replace(",",".",$objRhtNac->total);
$trRhtNacAt=$vlRhtNacAt*0.2;
$corRhtNacAt=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Bf")){ $vlRhtNacBf=$vlRhtNacBf+str_replace(",",".",$objRhtNac->total);$corRhtNacBf=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Bm")){ $vlRhtNacBm=$vlRhtNacBm+str_replace(",",".",$objRhtNac->total);$corRhtNacBm=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Boc")){ $vlRhtNacBoc=$vlRhtNacBoc+str_replace(",",".",$objRhtNac->total);$corRhtNacBoc=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Cic")){ $vlRhtNacCic=$vlRhtNacCic+str_replace(",",".",$objRhtNac->total);$corRhtNacCic=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Esg")){ $vlRhtNacEsg=$vlRhtNacEsg+str_replace(",",".",$objRhtNac->total);$corRhtNacEsg=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Fuc")){ $vlRhtNacFuc=$vlRhtNacFuc+str_replace(",",".",$objRhtNac->total);$corRhtNacFuc=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Fus")){ $vlRhtNacFus=$vlRhtNacFus+str_replace(",",".",$objRhtNac->total);$corRhtNacFus=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Gof")){ $vlRhtNacGof=$vlRhtNacGof+str_replace(",",".",$objRhtNac->total);$corRhtNacGof=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Gom")){ $vlRhtNacGom=$vlRhtNacGom+str_replace(",",".",$objRhtNac->total);$corRhtNacGom=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Halt")){ $vlRhtNacHalt=$vlRhtNacHalt+str_replace(",",".",$objRhtNac->total);$corRhtNacHalt=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Hip")){ $vlRhtNacHip=$vlRhtNacHip+str_replace(",",".",$objRhtNac->total);$corRhtNacHip=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Jud")){ $vlRhtNacJud=$vlRhtNacJud+str_replace(",",".",$objRhtNac->total);$corRhtNacJud=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Nat")){ $vlRhtNacNat=$vlRhtNacNat+str_replace(",",".",$objRhtNac->total);$corRhtNacNat=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Can")){ $vlRhtNacCan=$vlRhtNacCan+str_replace(",",".",$objRhtNac->total);$corRhtNacCan=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Thl")){ $vlRhtNacThl=$vlRhtNacThl+str_replace(",",".",$objRhtNac->total);$corRhtNacThl=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Rem")){ $vlRhtNacRem=$vlRhtNacRem+str_replace(",",".",$objRhtNac->total);$corRhtNacRem=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Rug")){ $vlRhtNacRug=$vlRhtNacRug+str_replace(",",".",$objRhtNac->total);$corRhtNacRug=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Ten")){ $vlRhtNacTen=$vlRhtNacTen+str_replace(",",".",$objRhtNac->total);$corRhtNacTen=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Tar")){ $vlRhtNacTar=$vlRhtNacTar+str_replace(",",".",$objRhtNac->total);$corRhtNacTar=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Tes")){ $vlRhtNacTes=$vlRhtNacTes+str_replace(",",".",$objRhtNac->total);$corRhtNacTes=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Vel")){ $vlRhtNacVel=$vlRhtNacVel+str_replace(",",".",$objRhtNac->total);$corRhtNacVel=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Vof")){ $vlRhtNacVof=$vlRhtNacVof+str_replace(",",".",$objRhtNac->total);$corRhtNacVof=""; }}
while($objRhtNac=mysql_fetch_object($sqlRhtNac)){ if(strtoupper($objRhtNac->modal)== strtoupper("Vom")){ $vlRhtNacVom=$vlRhtNacVom+str_replace(",",".",$objRhtNac->total);$corRhtNacVom=""; }}
//Fim do calculo de tributos RH
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("At")){ $vlRhtIntAt=$vlRhtIntAt+str_replace(",",".",$objRhtInt->total);$corRhtIntAt=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Bf")){ $vlRhtIntBf=$vlRhtIntBf+str_replace(",",".",$objRhtInt->total);$corRhtIntBf=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Bm")){ $vlRhtIntBm=$vlRhtIntBm+str_replace(",",".",$objRhtInt->total);$corRhtIntBm=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Boc")){ $vlRhtIntBoc=$vlRhtIntBoc+str_replace(",",".",$objRhtInt->total);$corRhtIntBoc=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Cic")){ $vlRhtIntCic=$vlRhtIntCic+str_replace(",",".",$objRhtInt->total);$corRhtIntCic=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Esg")){ $vlRhtIntEsg=$vlRhtIntEsg+str_replace(",",".",$objRhtInt->total);$corRhtIntEsg=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Fuc")){ $vlRhtIntFuc=$vlRhtIntFuc+str_replace(",",".",$objRhtInt->total);$corRhtIntFuc=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Fus")){ $vlRhtIntFus=$vlRhtIntFus+str_replace(",",".",$objRhtInt->total);$corRhtIntFus=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Gof")){ $vlRhtIntGof=$vlRhtIntGof+str_replace(",",".",$objRhtInt->total);$corRhtIntGof=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Gom")){ $vlRhtIntGom=$vlRhtIntGom+str_replace(",",".",$objRhtInt->total);$corRhtIntGom=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Halt")){ $vlRhtIntHalt=$vlRhtIntHalt+str_replace(",",".",$objRhtInt->total);$corRhtIntHalt=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Hip")){ $vlRhtIntHip=$vlRhtIntHip+str_replace(",",".",$objRhtInt->total);$corRhtIntHip=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Jud")){ $vlRhtIntJud=$vlRhtIntJud+str_replace(",",".",$objRhtInt->total);$corRhtIntJud=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Nat")){ $vlRhtIntNat=$vlRhtIntNat+str_replace(",",".",$objRhtInt->total);$corRhtIntNat=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Can")){ $vlRhtIntCan=$vlRhtIntCan+str_replace(",",".",$objRhtInt->total);$corRhtIntCan=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Thl")){ $vlRhtIntThl=$vlRhtIntThl+str_replace(",",".",$objRhtInt->total);$corRhtIntThl=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Rem")){ $vlRhtIntRem=$vlRhtIntRem+str_replace(",",".",$objRhtInt->total);$corRhtIntRem=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Rug")){ $vlRhtIntRug=$vlRhtIntRug+str_replace(",",".",$objRhtInt->total);$corRhtIntRug=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Ten")){ $vlRhtIntTen=$vlRhtIntTen+str_replace(",",".",$objRhtInt->total);$corRhtIntTen=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Tar")){ $vlRhtIntTar=$vlRhtIntTar+str_replace(",",".",$objRhtInt->total);$corRhtIntTar=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Tes")){ $vlRhtIntTes=$vlRhtIntTes+str_replace(",",".",$objRhtInt->total);$corRhtIntTes=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Vel")){ $vlRhtIntVel=$vlRhtIntVel+str_replace(",",".",$objRhtInt->total);$corRhtIntVel=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Vof")){ $vlRhtIntVof=$vlRhtIntVof+str_replace(",",".",$objRhtInt->total);$corRhtIntVof=""; }}
while($objRhtInt=mysql_fetch_object($sqlRhtInt)){ if(strtoupper($objRhtInt->modal)== strtoupper("Vom")){ $vlRhtIntVom=$vlRhtIntVom+str_replace(",",".",$objRhtInt->total);$corRhtIntVom=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("At")){ $vlMatAt=$vlMatAt+str_replace(",",".",$objMat->total);$corMatAt=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Bf")){ $vlMatBf=$vlMatBf+str_replace(",",".",$objMat->total);$corMatBf=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Bm")){ $vlMatBm=$vlMatBm+str_replace(",",".",$objMat->total);$corMatBm=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Boc")){ $vlMatBoc=$vlMatBoc+str_replace(",",".",$objMat->total);$corMatBoc=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Cic")){ $vlMatCic=$vlMatCic+str_replace(",",".",$objMat->total);$corMatCic=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Esg")){ $vlMatEsg=$vlMatEsg+str_replace(",",".",$objMat->total);$corMatEsg=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Fuc")){ $vlMatFuc=$vlMatFuc+str_replace(",",".",$objMat->total);$corMatFuc=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Fus")){ $vlMatFus=$vlMatFus+str_replace(",",".",$objMat->total);$corMatFus=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Gof")){ $vlMatGof=$vlMatGof+str_replace(",",".",$objMat->total);$corMatGof=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Gom")){ $vlMatGom=$vlMatGom+str_replace(",",".",$objMat->total);$corMatGom=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Halt")){ $vlMatHalt=$vlMatHalt+str_replace(",",".",$objMat->total);$corMatHalt=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Hip")){ $vlMatHip=$vlMatHip+str_replace(",",".",$objMat->total);$corMatHip=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Jud")){ $vlMatJud=$vlMatJud+str_replace(",",".",$objMat->total);$corMatJud=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Nat")){ $vlMatNat=$vlMatNat+str_replace(",",".",$objMat->total);$corMatNat=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Can")){ $vlMatCan=$vlMatCan+str_replace(",",".",$objMat->total);$corMatCan=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Thl")){ $vlMatThl=$vlMatThl+str_replace(",",".",$objMat->total);$corMatThl=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Rem")){ $vlMatRem=$vlMatRem+str_replace(",",".",$objMat->total);$corMatRem=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Rug")){ $vlMatRug=$vlMatRug+str_replace(",",".",$objMat->total);$corMatRug=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Ten")){ $vlMatTen=$vlMatTen+str_replace(",",".",$objMat->total);$corMatTen=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Tar")){ $vlMatTar=$vlMatTar+str_replace(",",".",$objMat->total);$corMatTar=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Tes")){ $vlMatTes=$vlMatTes+str_replace(",",".",$objMat->total);$corMatTes=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Vel")){ $vlMatVel=$vlMatVel+str_replace(",",".",$objMat->total);$corMatVel=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Vof")){ $vlMatVof=$vlMatVof+str_replace(",",".",$objMat->total);$corMatVof=""; }}
while($objMat=mysql_fetch_object($sqlMat)){ if(strtoupper($objMat->modal)== strtoupper("Vom")){ $vlMatVom=$vlMatVom+str_replace(",",".",$objMat->total);$corMatVom=""; }}
?>